README.md
lib/index.js
package.json
test/fixtures/defs/pets.json
test/fixtures/defs/pets.yaml
test/test-swaggerize-hapi.js

This PR also contains commits that reflect adding custom query parameter validation for arrays.
This feature was added, and is now stripped out given that the api specification can be changed to reflect the requirements of the framework.
In particular, for api, arrays are passed as the `multi` option for `collectionFormat` in the api specification.
The bug, https://github.com/krakenjs/swaggerize-hapi/issues/25, was originally opened because `swagger-ui` doesn't properly construct requests to respect the `collectionFormat` in the api spec. This has been fixed int he latest release.

Add YAML and CORS support

---

lib/index.js
package.json
test/fixtures/defs/pets.json
test/test-swaggerize-hapi.js

Form data validates differently due to the presence of `file` types. Unfortunately I have to recreate the validation of `payload` by gather individual validators and executing them directly.

Fix form data

---

README.md

The Hapi API for registering plugins has changed since this was written.

Manual usage instructions out of date

---

.travis.yml
package.json

- hapi is only needed for tests
- Upgrading a dependency without releasing a new version fucked me :)

Hapi dependency

---

CHANGELOG.md
lib/index.js
test/fixtures/defs/pets_authed.json
test/test-swaggerize-hapi.js

- Fix for #50 
- Added `headers` validate config as a `Joi` object with `allowUnknown: true` option.

Adding a header parameter disallows other unspecified headers

---

LICENSE.txt
package.json

I was alerted by a tool we use that this npm module is unlicensed.
The Apache License, Version 2.0 seems to be what you use in your modules. Please have a look and see if it is correct. I copied the license from `swaggerize-express`.

Add license

---

lib/index.js

Meaningless trailing slashes in URLs should be avoided. If someone wants to support URLs with trailing slashes, it can be easily achieved with following server extension:
```
server.ext('onRequest', function (request, reply) {
request.path = request.path.replace(/\/$/, '');
return reply.continue();
});
```

#51 Remove trailing slash from docspath

---

package.json

- Made the engine restriction be >=4.x
Was having problems installing with yarn with Node v7.1.0.

Engines Restriction >=4.x

---

lib/index.js
package.json

- Convert objects to Joi schemas by passing the objects to `Joi.object()`
- Move construction of validators to a separate function because the linter complained about cyclomatic complexity

Ensure validators are Joi schemas

---

.gitignore
lib/routes.js
test/test-hapi-openapi.js

Fix #117 
Since hapi doesn't support empty descriptions (but OpenAPI does), this PR skips those empty descriptions from the OpenAPI definition when it is building the routes.
I've added a couple of specs for this case as well as ignored the `vscode` folder.

Skip empty descriptions for routes

---

package.json

During install, I noticed that there were several security vulnerabilities. Turns out these were only with the `nyc` dev dependency, but it's an easy update and prevents scary warnings during local install.

Remediate security vulnerabilities

---

README.md
lib/index.js
test/test-hapi-openapi.js

We need the ability to put the docs at a path that is not rooted at the basePath of the swagger spec.
see https://github.com/krakenjs/hapi-openapi/issues/149
closes #149

Added prefixBasePath to docs option

---

lib/validators.js
test/test-validators.js

If you have a multi-segment path defined (/api/v1/proxy/{path*}) it breaks when it creates the validator due to it creating the param name as "path*" instead of "path". As multi-segment parameters can also have a repeat variable (path*2 as example) replacing the path variable name needs to take this into account.

Fixes #151

---

lib/routes.js
lib/validators.js
test/test-hapi-openapi.js

This ensures it is possible to allow unknown properties in request bodies (Postel’s Law), by respecting the `x-hapi-options` option.
---
**Discussion**
In general, one could consider making `allowUnknown: true` the default behavior, but I guess that would be considered a breaking change.
*Some notes from the thought processes around this change*:
* The server wide route option (where this could be set) is apparently not respected by hapi-openapi (probably because validation is overwritten?). Otherwise, that would've been a nice way to avoid this custom property.
* Just providing the validation option does not seem to cut it, since `options.validator` is overwritten. Avoiding overwriting the provided option (`options.validate = Object.assign({}, v.validate, options.validate);` did not …

fix(validation): respect `allowUnknown` route property

---

.travis.yml
README.md
lib/index.js
lib/routes.js
lib/validators.js
package.json
test/fixtures/lib/stub-auth-token-scheme.js
test/fixtures/lib/xauth-scheme.js
test/fixtures/lib/xauth-strategy.js
test/test-auth.js
test/test-forms.js
test/test-hapi-openapi.js
test/test-validators.js
test/test_xoptions.js

**Description of changes:**
This PR updates several dependencies (list below). The hapi upgrade includes two important changes:
1. There is no longer a way to query the strategies registered with the server. The previous behavior allowed hapi-openapi to issue a warning that an auth strategy was not registered, then continue creating the route without the specified auth options. With this change, the route options will be added as long as they are specified. If the auth strategy is not registered, then an error will be thrown when registering the route. This seems to be inline with the existing text in README.md.
2. Hapi 19 no longer allows uncompiled top-level validation schemas unless a validator is configured with the server. In previous versions, Joi was used by default. To address …

Upgrade dependencies to support hapi 19

---

.vscode/launch.json
lib/validators.js
test/test-hapi-openapi.js

After commit https://github.com/krakenjs/hapi-openapi/commit/429bfbfa53c8b8f1f5574f0e9447a3acdc669474, Joi object unknown method was called for all input schemas. This results in a runtime error for array input schema. This commit only invokes unknown method for object schema type. For convenience VS Code launch file to debug tape tests is also included.

Fixed failing `unknown` call for array schema

---

lib/validators.js
test/test-validators.js

Addresses https://github.com/krakenjs/hapi-openapi/issues/166
Previously, two things were working together to create this result:
1. The `coercion` function would return `undefined` for an empty object or array value for body parameters (`parameter.schema` exists). 
2. The result of running the `coercion` function ('undefined' in this case) was sent to `schema.validate`. Because this function is `await`ed, the actual value is returned, and is subsequently inspected for an `error` property. Since the value is `undefined`, this throws an unexpected error.
The fix applied is:
1. Don't coerce empty objects or arrays into `undefined`. Just return the empty object/array. 
2. Don't `await` calls to `validate`. This is not as async function, so `await` is not needed. In this case, `await`ing …

Empty object coercion

---

lib/validators.js
test/test-hapi-openapi.js

Addresses https://github.com/krakenjs/hapi-openapi/issues/179
To prevent optional parameters not present in the request from having their keys added to `request.orig`, I added an explicit check for `undefined` in the `routeExt` function before adding the key to the request, preserving the original request.
This also fixes issues found integrating hapi-openapi and hapi-pagination.

Don't set undefined parameters on request in "routeExt"

---

.eslintrc
lib/index.js
lib/routes.js
lib/validators.js
package.json
test/fixtures/lib/stub-auth-token-scheme.js
test/fixtures/openapi3/defs/pets-types.yaml
test/fixtures/openapi3/defs/pets.yaml
test/fixtures/openapi3/defs/pets_authed.yaml
test/test-auth.js
test/test-hapi-openapi3.js

This pull request adds initial support for OpenAPI 3.0. 
enjoi dependency is a placeholder to be updated later if/when https://github.com/tlivings/enjoi/pull/92 is merged.

Initial support for OpenAPI 3.0

---

lib/index.js
lib/validators.js
package.json

Hello.
I've been trying to use this module, but it doesn't seem to work due to hapi and this module using different joi packages (this repo used @hapi/joi, hapi now uses joi)
Also updated enjoi to a version that also uses joi instead of @hapi/joi

Move from @hapi/join to joi to avoid error on mixing different version of joi schemas

---

README.md

Minor documentation change in the README that shows a complete but minimal hapi server.

updated README to add runnable hapi server example

---

lib/routes.js
test/fixtures/defs/pets_authed.json
test/fixtures/lib/stub-auth-token-scheme.js
test/test-auth.js

security:
A declaration of which security mechanisms can be used across the API. The list of values includes alternative security requirement objects that can be used. Only one of the security requirement objects need to be satisfied to authorize a request. Individual operations can override this definition. **To make security optional, an empty security requirement ({}) can be included in the array.**
closes #189

support optional security - close #189
